<a href="https://colab.research.google.com/github/ishtiaque7/Artificial_Intelligence_AILab/blob/main/AI_lab_2_212_15_4217.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np

arr2 = np.array(25)

print(arr2)

25


In [4]:
arr2.ndim

0

In [7]:
import numpy as np

m = np.array([[1, 2, 3], [4, 5, 6]])

print(m)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
arr_3d.ndim

3

In [10]:
arr=np.array([2, 5, 9, 8, 3])
arr[2]

9

In [11]:
print(arr[2]+arr[0])

11


In [13]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print('3rd element on 2nd row: ', m[1, 2])

3rd element on 2nd row:  6


In [18]:

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("The array element is: ",arr3d[1, 0, 2])

The array element is:  9


In [22]:
m[1:2]
#2nd row and 3 coloumn

array([[4, 5, 6]])

In [23]:
print(arr[:4])

[2 5 9 8]


In [24]:
print(arr[-3:-1])

[9 8]


In [25]:
print(arr[1:5:2])
#starting from 1 index and end 4 and difference of the index is 2

[5 8]


In [26]:
print(arr[::2])
# difference the element by 2

[2 9 3]


In [28]:
#m is 2 d array so ....
print(m[1, 1:4])


[5 6]


In [29]:
ap = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(ap[0:2, 2])

[3 8]


In [30]:
slc = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(slc[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [31]:
str = np.array([1, 2, 3, 4], dtype='S')

print(str)
print(str.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [33]:
#shallow Copy
s_arr = np.array([1, 2, 3, 4, 5])
x = s_arr.copy()
s_arr[0] = 42

print(s_arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [35]:
#Deep copy

D_arr = np.array([5,10,20,30,5,2,7,8,9,1])
x2 = D_arr.view()
D_arr[0] = 33

print(D_arr)
print(x2)

[33 10 20 30  5  2  7  8  9  1]
[33 10 20 30  5  2  7  8  9  1]


In [36]:
arr.shape

(5,)

In [37]:
m.shape

(2, 3)

In [38]:
arr3d.shape

(2, 2, 3)

In [42]:
arr_1d = np.array([1,5,10,13,25,1,81,5,1,56,185,44])

newarr = arr_1d.reshape(4, 3)

print(newarr)

[[  1   5  10]
 [ 13  25   1]
 [ 81   5   1]
 [ 56 185  44]]


In [44]:

arr3 = np.array([1,5,10,13,25,1,81,5,1,56,185,44])

newarr = arr3.reshape(2, 3, 2)

print(newarr)

[[[  1   5]
  [ 10  13]
  [ 25   1]]

 [[ 81   5]
  [  1  56]
  [185  44]]]


In [45]:
ex3 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = ex3.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
newarr = m.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [49]:
newa=arr3.reshape(-1)
newa

array([  1,   5,  10,  13,  25,   1,  81,   5,   1,  56, 185,  44])

In [54]:
a = np.array([1,5,10,13,25,1,81,5,1,56,185,44])

for x in a:
  print(x)

1
5
10
13
25
1
81
5
1
56
185
44


In [55]:
arr = np.array([[4,5,9], [10,20,55]])

for x in arr:
  for y in x:
    print(y)

4
5
9
10
20
55


In [56]:
for x in arr3d:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [57]:
arr1 = np.array([5,7,12])

arr2 = np.array([8,71,33,20])

arr = np.concatenate((arr1, arr2))

print(arr)

[ 5  7 12  8 71 33 20]


In [58]:
arr1 = np.array([[5, 10], [15, 20]])

arr2 = np.array([[15, 26], [37, 58]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[ 5 10 15 26]
 [15 20 37 58]]


In [59]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [60]:
x = np.where(m%2 == 0)

print(x)

(array([0, 1, 1]), array([1, 0, 2]))


In [61]:
a = np.array([1,5,10,13,25,1,81,5,1,56,185,44])

print(np.sort(a))

[  1   1   1   5   5  10  13  25  44  56  81 185]


In [66]:
arr = np.array([[100, 12, 44], [5, 25, 1]])
print(np.sort(arr))


[[ 12  44 100]
 [  1   5  25]]
